paths:
  uploads: public/uploads
  static: ""

collections_config:
  pages:
    path: content
    glob: "**/*.json"
    name: "Pagina's"
    icon: wysiwyg
    output: false

    # ðŸ‘‡ DEZE REGEL MISTE!
    # Dit koppelt je 'home.json' aan je homepage URL.
    # Zonder dit werkt de Visual Editor niet.
    url: /

    _enabled_editors:
      - visual
      - data
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false

# Dit zorgt dat die mappen 'sections', 'three' en 'App' verdwijnen uit je lijst
source_editor:
  ignore:
    - "node_modules"
    - ".git"
    - "src"
    - "*.tsx"
    - "*.ts"
    - "package.json"
    - "tsconfig.json"
    - "vite.config.ts"

timezone: Europe/Amsterdam

markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: false
    code_block_fences: "```"
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
